### ISSUE TITLE
Import button does nothing in Blender with Substance Painter version 2018.3

### ISSUE THREAD

**Issue by TheRealRino** [DigiKrafting/blender_addon_substance_painter#7]
Hi DigiKrafting,

Awesome addon. The exporting works well for the current release of Blender 2.80, except, the import doesn't create node inputs of a selected object and does nothing to the exported textures from my Substance 2018.3. Do let me know if I have missed something which caused it so.

Steps to re-create:
1. Select a UV unwrapped blender object and create a material
2. Click export to substance(selected)
3. In Substance 2018.3 save manually and export textures into the textures folder once done baking and texturing.
4. Import to substance(selected)

Thank you for the addon. Let me know if there are ways I can help support your development.

**Comment by DigiKrafting** [comment]
Hi  TheRealRino,

In SP 2018.1.0 to 2018.3.0 the project file name sent from blender is appended to the textures export path in SP which causes the addon not to know where the textures were created, please make sure you tick "2018.1.0-2018.3.0 Project File Fix" in the addon preferences and check the folder that is set in SP when exporting textures. This addon should work with any SP version since SP 2 when it was first created, I used it with every version since and there shouldn't be any issues when importing the textures into blender. Please let me know if this fixes the issue.

**Comment by TheRealRino** [comment]
Hi DigiKrafting,

Sorry I kept you hanging for a few days.

It does work now when I tried it on a new scene with a cube with the  "2018.1.0-2018.3.0 Project File Fix" ticked. Strangely that day I tried it and it doesn't do anything when importing(selected). Probably user error haha.

Thanks again.

**Comment by DigiKrafting** [comment]
Your welcome :)
